BEGIN;

CREATE TABLE tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guild_id text NOT NULL,
    creator_id text NOT NULL,
    editor text NOT NULL,

    trigger text NOT NULL,
    content text NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE (guild_id, trigger)
);

COMMIT;