BEGIN;

CREATE TABLE user_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL UNIQUE,

    timezone text, -- tz database timezone

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

COMMIT;