BEGIN;

CREATE TABLE quotes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    quote text NOT NULL,
    num int NOT NULL,

    quoter_id text NOT NULL, -- Person that quoted the message
    quoted_id text NOT NULL, -- Person that was quoted
    quoted_username text NOT NULL,

    guild_id text NOT NULL,
    channel_id text NOT NULL,
    message_id text NOT NULL UNIQUE,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE (num, guild_id)
);

CREATE TABLE guilds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guild_id text NOT NULL UNIQUE,

    do_quotes bool NOT NULL DEFAULT 'false',

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE discord_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id text NOT NULL UNIQUE,

    access_token text NOT NULL,
    refresh_token text NOT NULL,
    expiry timestamp NOT NULL,
    token_type text NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token text NOT NULL UNIQUE,
    data bytea NOT NULL,
    expiry timestamptz NOT NULL
);

COMMIT;