BEGIN;

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_name text NOT NULL,
    role_id text NOT NULL,
    guild_id text NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(role_id, guild_id)
);

COMMIT;