BEGIN;

CREATE TABLE quotes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    quote text NOT NULL,
    num bigint NOT NULL,

    guild_id text NOT NULL,
    channel_id text NOT NULL,
    message_id text NOT NULL UNIQUE,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE (num, guild_id)
);

COMMIT;