BEGIN;

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_id text NOT NULL,
    guild_id text NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(role_id, guild_id)
);

CREATE TABLE egoraptor_mentions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guild_id text NOT NULL,

    last_timestamp timestamptz NOT NULL,
    last_user text NOT NULL,
    count int NOT NULL,

    timeout_on_mention boolean NOT NULL DEFAULT 'false',
    timeout_length int NOT NULL DEFAULT '60',

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(guild_id)
);

COMMIT;