BEGIN;

ALTER TABLE egoraptor_mentions RENAME TO egoraptor_settings;

CREATE TABLE egoraptor_mentions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guild_id text NOT NULL,
    user_id text NOT NULL,
    count int NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(guild_id, user_id)
);

COMMIT;