// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	EgoraptorMentions string
	Quotes            string
	Roles             string
}{
	EgoraptorMentions: "egoraptor_mentions",
	Quotes:            "quotes",
	Roles:             "roles",
}
