// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DiscordTokens     string
	EgoraptorMentions string
	Guilds            string
	Quotes            string
	Roles             string
	Sessions          string
}{
	DiscordTokens:     "discord_tokens",
	EgoraptorMentions: "egoraptor_mentions",
	Guilds:            "guilds",
	Quotes:            "quotes",
	Roles:             "roles",
	Sessions:          "sessions",
}
