// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DiscordTokens     string
	EgoraptorMentions string
	EgoraptorSettings string
	Guilds            string
	Quotes            string
	RoleUpdater       string
	Roles             string
	Sessions          string
	Tags              string
	UserProfiles      string
}{
	DiscordTokens:     "discord_tokens",
	EgoraptorMentions: "egoraptor_mentions",
	EgoraptorSettings: "egoraptor_settings",
	Guilds:            "guilds",
	Quotes:            "quotes",
	RoleUpdater:       "role_updater",
	Roles:             "roles",
	Sessions:          "sessions",
	Tags:              "tags",
	UserProfiles:      "user_profiles",
}
