// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EgoraptorSetting is an object representing the database table.
type EgoraptorSetting struct {
	ID               int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	GuildID          string    `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	LastTimestamp    time.Time `boil:"last_timestamp" json:"last_timestamp" toml:"last_timestamp" yaml:"last_timestamp"`
	LastUser         string    `boil:"last_user" json:"last_user" toml:"last_user" yaml:"last_user"`
	Count            int       `boil:"count" json:"count" toml:"count" yaml:"count"`
	TimeoutOnMention bool      `boil:"timeout_on_mention" json:"timeout_on_mention" toml:"timeout_on_mention" yaml:"timeout_on_mention"`
	TimeoutLength    int       `boil:"timeout_length" json:"timeout_length" toml:"timeout_length" yaml:"timeout_length"`
	CreatedAt        time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt        time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *egoraptorSettingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L egoraptorSettingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EgoraptorSettingColumns = struct {
	ID               string
	GuildID          string
	LastTimestamp    string
	LastUser         string
	Count            string
	TimeoutOnMention string
	TimeoutLength    string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "id",
	GuildID:          "guild_id",
	LastTimestamp:    "last_timestamp",
	LastUser:         "last_user",
	Count:            "count",
	TimeoutOnMention: "timeout_on_mention",
	TimeoutLength:    "timeout_length",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

var EgoraptorSettingTableColumns = struct {
	ID               string
	GuildID          string
	LastTimestamp    string
	LastUser         string
	Count            string
	TimeoutOnMention string
	TimeoutLength    string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "egoraptor_settings.id",
	GuildID:          "egoraptor_settings.guild_id",
	LastTimestamp:    "egoraptor_settings.last_timestamp",
	LastUser:         "egoraptor_settings.last_user",
	Count:            "egoraptor_settings.count",
	TimeoutOnMention: "egoraptor_settings.timeout_on_mention",
	TimeoutLength:    "egoraptor_settings.timeout_length",
	CreatedAt:        "egoraptor_settings.created_at",
	UpdatedAt:        "egoraptor_settings.updated_at",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var EgoraptorSettingWhere = struct {
	ID               whereHelperint64
	GuildID          whereHelperstring
	LastTimestamp    whereHelpertime_Time
	LastUser         whereHelperstring
	Count            whereHelperint
	TimeoutOnMention whereHelperbool
	TimeoutLength    whereHelperint
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpertime_Time
}{
	ID:               whereHelperint64{field: "\"egoraptor_settings\".\"id\""},
	GuildID:          whereHelperstring{field: "\"egoraptor_settings\".\"guild_id\""},
	LastTimestamp:    whereHelpertime_Time{field: "\"egoraptor_settings\".\"last_timestamp\""},
	LastUser:         whereHelperstring{field: "\"egoraptor_settings\".\"last_user\""},
	Count:            whereHelperint{field: "\"egoraptor_settings\".\"count\""},
	TimeoutOnMention: whereHelperbool{field: "\"egoraptor_settings\".\"timeout_on_mention\""},
	TimeoutLength:    whereHelperint{field: "\"egoraptor_settings\".\"timeout_length\""},
	CreatedAt:        whereHelpertime_Time{field: "\"egoraptor_settings\".\"created_at\""},
	UpdatedAt:        whereHelpertime_Time{field: "\"egoraptor_settings\".\"updated_at\""},
}

// EgoraptorSettingRels is where relationship names are stored.
var EgoraptorSettingRels = struct {
}{}

// egoraptorSettingR is where relationships are stored.
type egoraptorSettingR struct {
}

// NewStruct creates a new relationship struct
func (*egoraptorSettingR) NewStruct() *egoraptorSettingR {
	return &egoraptorSettingR{}
}

// egoraptorSettingL is where Load methods for each relationship are stored.
type egoraptorSettingL struct{}

var (
	egoraptorSettingAllColumns            = []string{"id", "guild_id", "last_timestamp", "last_user", "count", "timeout_on_mention", "timeout_length", "created_at", "updated_at"}
	egoraptorSettingColumnsWithoutDefault = []string{"guild_id", "last_timestamp", "last_user", "count"}
	egoraptorSettingColumnsWithDefault    = []string{"id", "timeout_on_mention", "timeout_length", "created_at", "updated_at"}
	egoraptorSettingPrimaryKeyColumns     = []string{"id"}
	egoraptorSettingGeneratedColumns      = []string{}
)

type (
	// EgoraptorSettingSlice is an alias for a slice of pointers to EgoraptorSetting.
	// This should almost always be used instead of []EgoraptorSetting.
	EgoraptorSettingSlice []*EgoraptorSetting

	egoraptorSettingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	egoraptorSettingType                 = reflect.TypeOf(&EgoraptorSetting{})
	egoraptorSettingMapping              = queries.MakeStructMapping(egoraptorSettingType)
	egoraptorSettingPrimaryKeyMapping, _ = queries.BindMapping(egoraptorSettingType, egoraptorSettingMapping, egoraptorSettingPrimaryKeyColumns)
	egoraptorSettingInsertCacheMut       sync.RWMutex
	egoraptorSettingInsertCache          = make(map[string]insertCache)
	egoraptorSettingUpdateCacheMut       sync.RWMutex
	egoraptorSettingUpdateCache          = make(map[string]updateCache)
	egoraptorSettingUpsertCacheMut       sync.RWMutex
	egoraptorSettingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single egoraptorSetting record from the query.
func (q egoraptorSettingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EgoraptorSetting, error) {
	o := &EgoraptorSetting{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for egoraptor_settings")
	}

	return o, nil
}

// All returns all EgoraptorSetting records from the query.
func (q egoraptorSettingQuery) All(ctx context.Context, exec boil.ContextExecutor) (EgoraptorSettingSlice, error) {
	var o []*EgoraptorSetting

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EgoraptorSetting slice")
	}

	return o, nil
}

// Count returns the count of all EgoraptorSetting records in the query.
func (q egoraptorSettingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count egoraptor_settings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q egoraptorSettingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if egoraptor_settings exists")
	}

	return count > 0, nil
}

// EgoraptorSettings retrieves all the records using an executor.
func EgoraptorSettings(mods ...qm.QueryMod) egoraptorSettingQuery {
	mods = append(mods, qm.From("\"egoraptor_settings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"egoraptor_settings\".*"})
	}

	return egoraptorSettingQuery{q}
}

// FindEgoraptorSetting retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEgoraptorSetting(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*EgoraptorSetting, error) {
	egoraptorSettingObj := &EgoraptorSetting{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"egoraptor_settings\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, egoraptorSettingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from egoraptor_settings")
	}

	return egoraptorSettingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EgoraptorSetting) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no egoraptor_settings provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(egoraptorSettingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	egoraptorSettingInsertCacheMut.RLock()
	cache, cached := egoraptorSettingInsertCache[key]
	egoraptorSettingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			egoraptorSettingAllColumns,
			egoraptorSettingColumnsWithDefault,
			egoraptorSettingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(egoraptorSettingType, egoraptorSettingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(egoraptorSettingType, egoraptorSettingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"egoraptor_settings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"egoraptor_settings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into egoraptor_settings")
	}

	if !cached {
		egoraptorSettingInsertCacheMut.Lock()
		egoraptorSettingInsertCache[key] = cache
		egoraptorSettingInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the EgoraptorSetting.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EgoraptorSetting) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	egoraptorSettingUpdateCacheMut.RLock()
	cache, cached := egoraptorSettingUpdateCache[key]
	egoraptorSettingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			egoraptorSettingAllColumns,
			egoraptorSettingPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update egoraptor_settings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"egoraptor_settings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, egoraptorSettingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(egoraptorSettingType, egoraptorSettingMapping, append(wl, egoraptorSettingPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update egoraptor_settings row")
	}

	if !cached {
		egoraptorSettingUpdateCacheMut.Lock()
		egoraptorSettingUpdateCache[key] = cache
		egoraptorSettingUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q egoraptorSettingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for egoraptor_settings")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EgoraptorSettingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), egoraptorSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"egoraptor_settings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, egoraptorSettingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in egoraptorSetting slice")
	}

	return nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EgoraptorSetting) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no egoraptor_settings provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(egoraptorSettingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	egoraptorSettingUpsertCacheMut.RLock()
	cache, cached := egoraptorSettingUpsertCache[key]
	egoraptorSettingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			egoraptorSettingAllColumns,
			egoraptorSettingColumnsWithDefault,
			egoraptorSettingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			egoraptorSettingAllColumns,
			egoraptorSettingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert egoraptor_settings, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(egoraptorSettingPrimaryKeyColumns))
			copy(conflict, egoraptorSettingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"egoraptor_settings\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(egoraptorSettingType, egoraptorSettingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(egoraptorSettingType, egoraptorSettingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert egoraptor_settings")
	}

	if !cached {
		egoraptorSettingUpsertCacheMut.Lock()
		egoraptorSettingUpsertCache[key] = cache
		egoraptorSettingUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single EgoraptorSetting record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EgoraptorSetting) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no EgoraptorSetting provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), egoraptorSettingPrimaryKeyMapping)
	sql := "DELETE FROM \"egoraptor_settings\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from egoraptor_settings")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q egoraptorSettingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no egoraptorSettingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from egoraptor_settings")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EgoraptorSettingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), egoraptorSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"egoraptor_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, egoraptorSettingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from egoraptorSetting slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EgoraptorSetting) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEgoraptorSetting(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EgoraptorSettingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EgoraptorSettingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), egoraptorSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"egoraptor_settings\".* FROM \"egoraptor_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, egoraptorSettingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EgoraptorSettingSlice")
	}

	*o = slice

	return nil
}

// EgoraptorSettingExists checks if the EgoraptorSetting row exists.
func EgoraptorSettingExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"egoraptor_settings\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if egoraptor_settings exists")
	}

	return exists, nil
}

// Exists checks if the EgoraptorSetting row exists.
func (o *EgoraptorSetting) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EgoraptorSettingExists(ctx, exec, o.ID)
}
