// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// RoleUpdateSetting is an object representing the database table.
type RoleUpdateSetting struct {
	ID            int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	GuildID       string    `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	RoleID        string    `boil:"role_id" json:"role_id" toml:"role_id" yaml:"role_id"`
	DoUpdates     bool      `boil:"do_updates" json:"do_updates" toml:"do_updates" yaml:"do_updates"`
	LastTimestamp time.Time `boil:"last_timestamp" json:"last_timestamp" toml:"last_timestamp" yaml:"last_timestamp"`
	SteamUserID   string    `boil:"steam_user_id" json:"steam_user_id" toml:"steam_user_id" yaml:"steam_user_id"`
	SteamAppID    int       `boil:"steam_app_id" json:"steam_app_id" toml:"steam_app_id" yaml:"steam_app_id"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *roleUpdateSettingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L roleUpdateSettingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RoleUpdateSettingColumns = struct {
	ID            string
	GuildID       string
	RoleID        string
	DoUpdates     string
	LastTimestamp string
	SteamUserID   string
	SteamAppID    string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	GuildID:       "guild_id",
	RoleID:        "role_id",
	DoUpdates:     "do_updates",
	LastTimestamp: "last_timestamp",
	SteamUserID:   "steam_user_id",
	SteamAppID:    "steam_app_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var RoleUpdateSettingTableColumns = struct {
	ID            string
	GuildID       string
	RoleID        string
	DoUpdates     string
	LastTimestamp string
	SteamUserID   string
	SteamAppID    string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "role_update_settings.id",
	GuildID:       "role_update_settings.guild_id",
	RoleID:        "role_update_settings.role_id",
	DoUpdates:     "role_update_settings.do_updates",
	LastTimestamp: "role_update_settings.last_timestamp",
	SteamUserID:   "role_update_settings.steam_user_id",
	SteamAppID:    "role_update_settings.steam_app_id",
	CreatedAt:     "role_update_settings.created_at",
	UpdatedAt:     "role_update_settings.updated_at",
}

// Generated where

var RoleUpdateSettingWhere = struct {
	ID            whereHelperint64
	GuildID       whereHelperstring
	RoleID        whereHelperstring
	DoUpdates     whereHelperbool
	LastTimestamp whereHelpertime_Time
	SteamUserID   whereHelperstring
	SteamAppID    whereHelperint
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperint64{field: "\"role_update_settings\".\"id\""},
	GuildID:       whereHelperstring{field: "\"role_update_settings\".\"guild_id\""},
	RoleID:        whereHelperstring{field: "\"role_update_settings\".\"role_id\""},
	DoUpdates:     whereHelperbool{field: "\"role_update_settings\".\"do_updates\""},
	LastTimestamp: whereHelpertime_Time{field: "\"role_update_settings\".\"last_timestamp\""},
	SteamUserID:   whereHelperstring{field: "\"role_update_settings\".\"steam_user_id\""},
	SteamAppID:    whereHelperint{field: "\"role_update_settings\".\"steam_app_id\""},
	CreatedAt:     whereHelpertime_Time{field: "\"role_update_settings\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"role_update_settings\".\"updated_at\""},
}

// RoleUpdateSettingRels is where relationship names are stored.
var RoleUpdateSettingRels = struct {
}{}

// roleUpdateSettingR is where relationships are stored.
type roleUpdateSettingR struct {
}

// NewStruct creates a new relationship struct
func (*roleUpdateSettingR) NewStruct() *roleUpdateSettingR {
	return &roleUpdateSettingR{}
}

// roleUpdateSettingL is where Load methods for each relationship are stored.
type roleUpdateSettingL struct{}

var (
	roleUpdateSettingAllColumns            = []string{"id", "guild_id", "role_id", "do_updates", "last_timestamp", "steam_user_id", "steam_app_id", "created_at", "updated_at"}
	roleUpdateSettingColumnsWithoutDefault = []string{"guild_id", "role_id", "steam_user_id", "steam_app_id"}
	roleUpdateSettingColumnsWithDefault    = []string{"id", "do_updates", "last_timestamp", "created_at", "updated_at"}
	roleUpdateSettingPrimaryKeyColumns     = []string{"id"}
	roleUpdateSettingGeneratedColumns      = []string{}
)

type (
	// RoleUpdateSettingSlice is an alias for a slice of pointers to RoleUpdateSetting.
	// This should almost always be used instead of []RoleUpdateSetting.
	RoleUpdateSettingSlice []*RoleUpdateSetting

	roleUpdateSettingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	roleUpdateSettingType                 = reflect.TypeOf(&RoleUpdateSetting{})
	roleUpdateSettingMapping              = queries.MakeStructMapping(roleUpdateSettingType)
	roleUpdateSettingPrimaryKeyMapping, _ = queries.BindMapping(roleUpdateSettingType, roleUpdateSettingMapping, roleUpdateSettingPrimaryKeyColumns)
	roleUpdateSettingInsertCacheMut       sync.RWMutex
	roleUpdateSettingInsertCache          = make(map[string]insertCache)
	roleUpdateSettingUpdateCacheMut       sync.RWMutex
	roleUpdateSettingUpdateCache          = make(map[string]updateCache)
	roleUpdateSettingUpsertCacheMut       sync.RWMutex
	roleUpdateSettingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single roleUpdateSetting record from the query.
func (q roleUpdateSettingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*RoleUpdateSetting, error) {
	o := &RoleUpdateSetting{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for role_update_settings")
	}

	return o, nil
}

// All returns all RoleUpdateSetting records from the query.
func (q roleUpdateSettingQuery) All(ctx context.Context, exec boil.ContextExecutor) (RoleUpdateSettingSlice, error) {
	var o []*RoleUpdateSetting

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RoleUpdateSetting slice")
	}

	return o, nil
}

// Count returns the count of all RoleUpdateSetting records in the query.
func (q roleUpdateSettingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count role_update_settings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q roleUpdateSettingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if role_update_settings exists")
	}

	return count > 0, nil
}

// RoleUpdateSettings retrieves all the records using an executor.
func RoleUpdateSettings(mods ...qm.QueryMod) roleUpdateSettingQuery {
	mods = append(mods, qm.From("\"role_update_settings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"role_update_settings\".*"})
	}

	return roleUpdateSettingQuery{q}
}

// FindRoleUpdateSetting retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRoleUpdateSetting(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*RoleUpdateSetting, error) {
	roleUpdateSettingObj := &RoleUpdateSetting{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"role_update_settings\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, roleUpdateSettingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from role_update_settings")
	}

	return roleUpdateSettingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RoleUpdateSetting) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no role_update_settings provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(roleUpdateSettingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	roleUpdateSettingInsertCacheMut.RLock()
	cache, cached := roleUpdateSettingInsertCache[key]
	roleUpdateSettingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			roleUpdateSettingAllColumns,
			roleUpdateSettingColumnsWithDefault,
			roleUpdateSettingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(roleUpdateSettingType, roleUpdateSettingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(roleUpdateSettingType, roleUpdateSettingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"role_update_settings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"role_update_settings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into role_update_settings")
	}

	if !cached {
		roleUpdateSettingInsertCacheMut.Lock()
		roleUpdateSettingInsertCache[key] = cache
		roleUpdateSettingInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the RoleUpdateSetting.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RoleUpdateSetting) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	roleUpdateSettingUpdateCacheMut.RLock()
	cache, cached := roleUpdateSettingUpdateCache[key]
	roleUpdateSettingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			roleUpdateSettingAllColumns,
			roleUpdateSettingPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update role_update_settings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"role_update_settings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, roleUpdateSettingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(roleUpdateSettingType, roleUpdateSettingMapping, append(wl, roleUpdateSettingPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update role_update_settings row")
	}

	if !cached {
		roleUpdateSettingUpdateCacheMut.Lock()
		roleUpdateSettingUpdateCache[key] = cache
		roleUpdateSettingUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q roleUpdateSettingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for role_update_settings")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RoleUpdateSettingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), roleUpdateSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"role_update_settings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, roleUpdateSettingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in roleUpdateSetting slice")
	}

	return nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RoleUpdateSetting) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no role_update_settings provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(roleUpdateSettingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	roleUpdateSettingUpsertCacheMut.RLock()
	cache, cached := roleUpdateSettingUpsertCache[key]
	roleUpdateSettingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			roleUpdateSettingAllColumns,
			roleUpdateSettingColumnsWithDefault,
			roleUpdateSettingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			roleUpdateSettingAllColumns,
			roleUpdateSettingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert role_update_settings, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(roleUpdateSettingPrimaryKeyColumns))
			copy(conflict, roleUpdateSettingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"role_update_settings\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(roleUpdateSettingType, roleUpdateSettingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(roleUpdateSettingType, roleUpdateSettingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert role_update_settings")
	}

	if !cached {
		roleUpdateSettingUpsertCacheMut.Lock()
		roleUpdateSettingUpsertCache[key] = cache
		roleUpdateSettingUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single RoleUpdateSetting record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RoleUpdateSetting) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no RoleUpdateSetting provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), roleUpdateSettingPrimaryKeyMapping)
	sql := "DELETE FROM \"role_update_settings\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from role_update_settings")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q roleUpdateSettingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no roleUpdateSettingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from role_update_settings")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RoleUpdateSettingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), roleUpdateSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"role_update_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, roleUpdateSettingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from roleUpdateSetting slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RoleUpdateSetting) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRoleUpdateSetting(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RoleUpdateSettingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RoleUpdateSettingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), roleUpdateSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"role_update_settings\".* FROM \"role_update_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, roleUpdateSettingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RoleUpdateSettingSlice")
	}

	*o = slice

	return nil
}

// RoleUpdateSettingExists checks if the RoleUpdateSetting row exists.
func RoleUpdateSettingExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"role_update_settings\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if role_update_settings exists")
	}

	return exists, nil
}

// Exists checks if the RoleUpdateSetting row exists.
func (o *RoleUpdateSetting) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return RoleUpdateSettingExists(ctx, exec, o.ID)
}
