// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type ErrorPage struct {
	BasePage
	ErrorHead string
	ErrorText string
}

func (p *ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
    <div class="container m-auto h-screen gap-y-4 grid grid-cols-1 place-content-center">
        <h1 class="text-gray-900 dark:text-white italic font-extrabold text-center text-4xl sm:text-6xl"> Uh oh sisters!</h1>
        <h2 class="text-gray-900 dark:text-white text-center text-3xl sm:text-5xl">`)
	qw422016.E().S(p.ErrorHead)
	qw422016.N().S(`</h2>
        `)
	if p.ErrorText != "" {
		qw422016.N().S(`
            <p class="text-gray-900 dark:text-white text-center text-2xl">`)
		qw422016.E().S(p.ErrorText)
		qw422016.N().S(`</p>
        `)
	}
	qw422016.N().S(`
        <a class="justify-self-center focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-500 dark:hover:bg-green-600 dark:focus:ring-green-800" href="/">Home</a>
    </div>
`)
}

func (p *ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *ErrorPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
