// Code generated by qtc from "guilds.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type Guild struct {
	ID        string
	Name      string
	AvatarURL string
}

type GuildsPage struct {
	BasePage
	Guilds []*Guild
}

func (p *GuildsPage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Guilds`)
}

func (p *GuildsPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *GuildsPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *GuildsPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
    <li class="container m-auto grid grid-cols-1 xl:grid-cols-3 place-content-center">
        <ul class="bg-slate-50 text-gray-900 dark:bg-stone-900 dark:text-white sm:rounded xl:col-start-2 xl:col-end-2 divide-y divide-stone-500">
            `)
	for _, g := range p.Guilds {
		qw422016.N().S(`
                <div class="bg-transparent hover:bg-slate-100 text-gray-900 hover:text-blue-400 hover:dark:bg-stone-950 dark:text-white">
                    <a href="/guild/`)
		qw422016.E().S(g.ID)
		qw422016.N().S(`>`)
		qw422016.E().S(g.Name)
		qw422016.N().S(`</a>
                </div>
            `)
	}
	qw422016.N().S(`
        </ul>
    </li>
`)
}

func (p *GuildsPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *GuildsPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
