// Code generated by qtc from "guilds.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import "github.com/aquilax/truncate"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type Guild struct {
	ID   string
	Name string
}

type GuildsPage struct {
	BasePage
	Guilds []*Guild
}

func (p *GuildsPage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Guilds`)
}

func (p *GuildsPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *GuildsPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *GuildsPage) StreamMeta(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
    `)
	qw422016.N().S(importFontAwesome())
	qw422016.N().S(`
`)
}

func (p *GuildsPage) WriteMeta(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamMeta(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *GuildsPage) Meta() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteMeta(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *GuildsPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
    <section class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-one-third">
                    <nav class="panel is-success">
                        <p class="panel-heading has-text-centered is-size-3">
                            Guilds
                        </p>
                        `)
	for _, g := range p.Guilds {
		qw422016.N().S(`
                            <a href="/guild/`)
		qw422016.E().S(g.ID)
		qw422016.N().S(`"class="panel-block">
                                <span class="panel-icon">
                                    <i class="fa-brands fa-discord" aria-hidden="true"></i>
                                </span>
                                `)
		qw422016.E().S(truncate.Truncate(g.Name, 32, "...", truncate.PositionEnd))
		qw422016.N().S(`
                            </a>
                        `)
	}
	qw422016.N().S(`
                    </nav>
                </div>
            </div>
        </div>
    </section>
`)
}

func (p *GuildsPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *GuildsPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
