// Code generated by qtc from "guilds.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type Guild struct {
	ID        string
	Name      string
	AvatarURL string
}

type GuildsPage struct {
	BasePage
	Guilds []*Guild
}

func (p *GuildsPage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Guilds`)
}

func (p *GuildsPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *GuildsPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *GuildsPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
    <div class="container mb-5 m-auto flex flex-col flex-wrap place-content-center gap-5 md:flex-row">
        `)
	for _, g := range p.Guilds {
		qw422016.N().S(`
            <a class="flex flex-col h-40 w-80 place-content-center rounded bg-green-500 hover:bg-green-600 text-3xl text-center text-white" href="/guild/`)
		qw422016.E().S(g.ID)
		qw422016.N().S(`">
                `)
		if g.AvatarURL != "" {
			qw422016.N().S(`
                    <img class="mx-auto my-3 rounded-full" src="`)
			qw422016.E().S(g.AvatarURL)
			qw422016.N().S(`" alt="The icon of the `)
			qw422016.E().S(g.Name)
			qw422016.N().S(` Discord guild" />
                `)
		} else {
			qw422016.N().S(`
                    `)
			streamtrunc(qw422016, g.Name)
			qw422016.N().S(`
                `)
		}
		qw422016.N().S(`
            </a>
        `)
	}
	qw422016.N().S(`
    </div>
`)
}

func (p *GuildsPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *GuildsPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
