// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type IndexPage struct {
	BasePage
}

func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Home`)
}

func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *IndexPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
    <section class="section">
        <div class="container has-text-centered">
        <h1 class="title">The Workingman's Discord Bot</h1>
        <h2 class="subtitle"><span class="has-text-success">Quotes</span>, <span class="has-text-success">custom
            roles</span>, and <span class="has-text-success">25 year old web comics</span>. Made for the blue collar by
            the blue collar.</h2>
        </div>
    </section>
    <img id="bot2-lance" class="is-hidden-mobile" src="/static/lance.png">
`)
}

func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *IndexPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
