// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type IndexPage struct {
	BasePage
}

func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
    <div class="grid grid-cols-1 h-screen text-center">
        <div class="m-auto">
            <h1 class="dark:text-white mx-6 text-4xl md:text-5xl lg:text-5xl">The Workingman's Discord Bot</h1>
            <h2 class="dark:text-white mx-6 mt-6 text-2xl">made for the blue-collar, by the blue-collar.</h2>
        </div>
        <div class="invisible lg:visible pt-6 justify-self-end">
            <img src="/static/lance.png">
        </div>
    </div>
`)
}

func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *IndexPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
